# OpenBao server configuration, bind-mounted read-only at
# /openbao/config/config.hcl. The image's entrypoint always starts
# `bao server -config=/openbao/config`, merging every file in that
# directory -- this is the only one.
#
# OpenBao is the MPL-licensed fork of HashiCorp Vault (BUSL-licensed since
# Vault 1.15). Same API, same `bao`/`vault` CLI surface, so Vault's own
# documentation mostly applies; where it does not, openbao.org is
# authoritative and the differences are called out below.

ui = true

listener "tcp" {
  address = "0.0.0.0:8200"

  # No TLS here on purpose. 8200 is never published (see CLAUDE.md
  # "Single-ingress rule"); nginx/conf.d/openbao.conf terminates TLS for
  # vault.infra.famillelallier.net, and apps on infra-net talk to
  # http://openbao:8200 directly.
  tls_disable = true

  # Lets Prometheus scrape /v1/sys/metrics without carrying a token, the
  # same posture as the seaweedfs /metrics endpoint: read-only
  # numbers, on a network nothing outside the stack can reach. Without it
  # the metrics endpoint is an authenticated one and the scrape is a 403.
  telemetry {
    unauthenticated_metrics_access = true
  }
}

storage "raft" {
  # /openbao/file is the image's own directory for this, created and owned
  # by the unprivileged `openbao` user it runs as. A named volume mounted
  # over an image directory inherits that ownership, so raft can write.
  path    = "/openbao/file"
  node_id = "infra-1"
}

# cluster_addr is *required* with raft storage, single node or not: it is
# what the node advertises to its peers, and OpenBao refuses to start
# without it. The cluster port is the listener's + 1.
cluster_addr = "http://openbao:8201"
api_addr     = "http://openbao:8200"

# --- Auto-unseal -----------------------------------------------------------
#
# Without this stanza OpenBao defaults to a Shamir seal: it comes up *sealed*
# after every restart and stays that way, refusing every request, until an
# operator feeds it unseal keys by hand. That is unworkable here, because
# `make up` force-recreates every container on every deploy (Portainer's
# git-redeploy always sets forceCreate=true -- see CLAUDE.md "Portainer-managed
# stack"), so the vault would be sealed after every single deploy of the
# whole stack.
#
# The `static` seal is OpenBao's built-in answer: the root key is encrypted
# with a 32-byte key read from openbao/seal.key in this checkout (gitignored,
# generated by scripts/gen-seal-key.sh via `make init` or `make seal-key`).
# It is deliberately a bind-mounted *file* rather than a value in .env:
# .env is handed to containers wholesale via env_file and shipped to
# Portainer as the stack env, and a key that decrypts the vault has no
# business in either -- the same reasoning that keeps PORTAINER_API_KEY in
# .portainer.env.
#
# Understand what this trades away: whoever holds openbao/seal.key and the
# openbao-data volume can decrypt the vault offline. That is the documented
# use for this seal type -- chaining OpenBao to an existing source of trust
# -- and here that source is the machine's own disk. Back the key up
# somewhere the volume is not: lose it and the vault is unrecoverable.
#
# To rotate: write the new key, set current_key/current_key_id to it and
# previous_key/previous_key_id to the old one, restart, then drop the
# previous_* pair once the restart succeeds.
seal "static" {
  current_key_id = "infra-1"
  current_key    = "file:///openbao/seal.key"
}

# --- Audit -----------------------------------------------------------------
#
# Declared here rather than enabled through the API, because OpenBao refuses
# API-created audit devices unless unsafe_allow_api_audit_creation is on --
# an audit device that the API can create, the API can also remove. Declared
# devices are (re-)applied when the active node starts and on SIGHUP, which
# is why scripts/vault-init.sh HUPs the container after initialising it.
#
# stdout, not a file: Alloy already collects every container's logs into
# Loki, so the audit trail lands in the same place as everything else and
# needs no volume of its own. Values are HMAC'd by OpenBao before they are
# written, so this logs who asked for what, never the secrets themselves.
audit "file" "to-stdout" {
  description = "Audit trail to stdout, collected into Loki by alloy."

  options {
    file_path = "stdout"
  }
}

telemetry {
  prometheus_retention_time = "24h"
  # Every series would otherwise carry the container's random hostname,
  # which changes on each force-recreate and breaks continuity in Grafana.
  disable_hostname = true
}
