server {
    listen 443 ssl;
    server_name minio-console.famillelallier.net;

    include /etc/nginx/snippets/ssl.conf;

    client_max_body_size 0;
    proxy_buffering off;
    proxy_request_buffering off;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream http://minio:9001;
        proxy_pass $upstream;
        include /etc/nginx/snippets/proxy.conf;
    }
}
