server {
    listen 443 ssl;
    server_name rabbitmq.infra.famillelallier.net;

    include /etc/nginx/snippets/ssl.conf;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream http://rabbitmq:15672;
        proxy_pass $upstream;
        include /etc/nginx/snippets/proxy.conf;
    }
}
