#!/usr/bin/env bash
# Create the `ea-obsidian` Keycloak client in the `ea` realm and write its
# generated secret into .env as EA_OBSIDIAN_OAUTH_CLIENT_SECRET.
#
# Why this exists: the `ea` realm was imported (commit 7d807d2) before
# ea-realm.json gained the ea-obsidian client (commit 86daf20), and
# `start --import-realm` is a no-op for a realm that already exists -- so
# the client was never created and oauth2-proxy-ea crash-loops on
# "missing setting: client-secret". Re-importing the whole realm would
# rotate ea-librechat / ea-pipelines secrets too, hence this narrow fix.
#
# Safe to re-run: creates the client and its audience mapper only if absent,
# always re-reads the secret and refreshes the .env line.
#
# Usage: scripts/provision-ea-obsidian-client.sh
set -euo pipefail
cd "$(dirname "$0")/.."

if [ ! -f .env ]; then
  echo "provision-ea-obsidian-client.sh: .env not found (run 'make init' first)" >&2
  exit 1
fi

set -a
source .env
set +a

: "${KEYCLOAK_ADMIN:?Set KEYCLOAK_ADMIN in .env}"
: "${KEYCLOAK_ADMIN_PASSWORD:?Set KEYCLOAK_ADMIN_PASSWORD in .env}"

kc() {
  docker compose exec -T keycloak /opt/keycloak/bin/kcadm.sh "$@"
}

kc config credentials --server http://localhost:8080 --realm master \
   --user "$KEYCLOAK_ADMIN" --password "$KEYCLOAK_ADMIN_PASSWORD"

# Mirrors the ea-obsidian block of keycloak/realm-import/ea-realm.json.
# Kept inline rather than jq-extracted so the script needs nothing but docker.
if ! kc get clients -r ea -q clientId=ea-obsidian --fields clientId 2>/dev/null | grep -q ea-obsidian; then
  echo "provision-ea-obsidian-client.sh: creating client ea-obsidian in realm ea..."
  kc create clients -r ea -f - <<'JSON'
{
  "clientId": "ea-obsidian",
  "name": "EA — Obsidian (oauth2-proxy gate)",
  "protocol": "openid-connect",
  "publicClient": false,
  "clientAuthenticatorType": "client-secret",
  "standardFlowEnabled": true,
  "directAccessGrantsEnabled": false,
  "implicitFlowEnabled": false,
  "serviceAccountsEnabled": false,
  "attributes": {
    "pkce.code.challenge.method": "S256",
    "post.logout.redirect.uris": "https://obsidian.infra.famillelallier.net"
  },
  "redirectUris": ["https://obsidian.infra.famillelallier.net/oauth2/callback"],
  "webOrigins": []
}
JSON
else
  echo "provision-ea-obsidian-client.sh: client ea-obsidian already exists, reusing it."
fi

CLIENT_UUID=$(kc get clients -r ea -q clientId=ea-obsidian --fields id --format csv --noquotes | tr -d '\r\n')
if [ -z "$CLIENT_UUID" ]; then
  echo "provision-ea-obsidian-client.sh: could not resolve the client's internal id" >&2
  exit 1
fi

# oauth2-proxy's keycloak-oidc provider rejects a token whose `aud` lacks its
# own client id ("audience ... [account] does not match", a 500 on
# /oauth2/callback). Keycloak stamps only `account` there without this mapper
# -- the same one jarvis-realm.json gives the jarvis client.
if ! kc get "clients/$CLIENT_UUID/protocol-mappers/models" -r ea --fields name 2>/dev/null | grep -q ea-obsidian-audience; then
  echo "provision-ea-obsidian-client.sh: adding audience mapper ea-obsidian-audience..."
  kc create "clients/$CLIENT_UUID/protocol-mappers/models" -r ea -f - <<'JSON'
{
  "name": "ea-obsidian-audience",
  "protocol": "openid-connect",
  "protocolMapper": "oidc-audience-mapper",
  "config": { "included.client.audience": "ea-obsidian", "id.token.claim": "true", "access.token.claim": "true" }
}
JSON
fi

SECRET=$(kc get "clients/$CLIENT_UUID/client-secret" -r ea --fields value --format csv --noquotes | tr -d '\r\n')
if [ -z "$SECRET" ]; then
  echo "provision-ea-obsidian-client.sh: could not read the client secret" >&2
  exit 1
fi

# Refresh (or append) the .env line without disturbing anything else.
if grep -q '^EA_OBSIDIAN_OAUTH_CLIENT_SECRET=' .env; then
  tmp=$(mktemp)
  grep -v '^EA_OBSIDIAN_OAUTH_CLIENT_SECRET=' .env > "$tmp"
  printf 'EA_OBSIDIAN_OAUTH_CLIENT_SECRET=%s\n' "$SECRET" >> "$tmp"
  cat "$tmp" > .env
  rm -f "$tmp"
else
  printf '\n# Generated by scripts/provision-ea-obsidian-client.sh (Keycloak realm "ea",\n# client ea-obsidian -> Credentials tab). Regenerate by re-running it.\nEA_OBSIDIAN_OAUTH_CLIENT_SECRET=%s\n' "$SECRET" >> .env
fi

echo "provision-ea-obsidian-client.sh: EA_OBSIDIAN_OAUTH_CLIENT_SECRET written to .env."
echo "Next: docker compose up -d oauth2-proxy-ea"
